import{useState,useMemo,useRef,useEffect,useCallback}from"react";
import*as d3 from"d3";

/* ── Design Tokens ── */
var P="#E87722",Dk="#0f1117",Dk2="#1a1d27",Dk3="#252836",Surf="#f8f9fb",Bdr="#e8eaef",Bdr2="#d1d5de",Tx="#0f1117",Tx2="#5f6577",Tx3="#9098a9",F="'DM Sans',system-ui,-apple-system,sans-serif";
var SEGMENTS=["Banking & Financial Services","Logistics & Transport","Retail & Consumer Networks","Industrial Production","Real Estate"];
var SUB_SEG={"Banking & Financial Services":["Financial service activities"],"Logistics & Transport":["Warehousing and support activities"],"Retail & Consumer Networks":["Retail trade"],"Industrial Production":["Basic metals","Computers & electronics","Motor vehicles"],"Real Estate":["Real estate activities"]};
var REGIONS=["Mazowieckie","Śląskie","Wielkopolskie","Małopolskie","Dolnośląskie","Łódzkie","Pomorskie","Zachodniopomorskie"];
var SEGC={"Banking & Financial Services":"#E87722","Retail & Consumer Networks":"#eab308","Industrial Production":"#8b5cf6","Logistics & Transport":"#06b6d4","Real Estate":"#ec4899"};
var SEG_W={"Banking & Financial Services":42,"Logistics & Transport":24,"Retail & Consumer Networks":20,"Industrial Production":10,"Real Estate":4};

/* ── New Stage System (per Atalian feedback) ── */
var STAGES=["New suspects","To be contacted","Contacted","Pre-qualified","Handed-over"];
var STAGE_C={"New suspects":"#8b5cf6","To be contacted":"#6b7280","Contacted":"#3b82f6","Pre-qualified":"#E87722","Handed-over":"#22c55e"};
var STAGE_IC={"New suspects":"★","To be contacted":"○","Contacted":"◐","Pre-qualified":"◉","Handed-over":"→"};

/* ── Qualification: Hot Lead / Cold Lead / Not Relevant (replaces SQL/MQL/NR) ── */
function calcWS(sc){var tw=0,tu=0;PQ.forEach(function(c){c.items.forEach(function(it){if(sc[it.id]){tw+=sc[it.id]*it.w;tu+=it.w}})});return tu?tw/tu:0}
function getQ(ws){if(ws>=3.8)return{label:"Hot Lead",short:"Hot",color:"#22c55e",bg2:"#dcfce7"};if(ws>=2.5)return{label:"Cold Lead",short:"Cold",color:"#3b82f6",bg2:"#dbeafe"};if(ws>0)return{label:"Not Relevant",short:"NR",color:"#ef4444",bg2:"#fee2e2"};return null}

function genCo(n){var pfx=["Pol","War","Krak","Gdań","Wrocł","Łódź","Pozn","Szcz","Lub","Kat","Bial","Czest","Rad","Tor","Kiel","Ols","Rzesz","Opol","Gliwi","Zabrz","Bydg","Tychy","Sosnow","Elbl","Płock","Tarn","Biel","Legn","Nowy","Stary","Wielk","Mało","Piotr","Siedl","Zamość","Radom","Toruń","Elblag"];var sfx=["Bank S.A.","Finance S.A.","Logistics Sp. z o.o.","Transport S.A.","Trade Sp. z o.o.","Retail S.A.","Metals Sp. z o.o.","Motors S.A.","Tech S.A.","Real Estate S.A.","Capital S.A.","Invest S.A.","Group S.A.","Services Sp. z o.o.","Holdings S.A.","Solutions S.A.","Partners S.A.","Management S.A.","Development S.A.","International S.A."];var co=[],u=new Set();var r=function(a,b){return Math.floor(Math.random()*(b-a+1))+a};var p=function(a){return a[Math.floor(Math.random()*a.length)]};var rf=function(a,b){return+(Math.random()*(b-a)+a).toFixed(2)};var skeys=Object.keys(SEG_W),stot=Object.values(SEG_W).reduce(function(a,b){return a+b},0);for(var i=0;i<n;i++){var nm;do{nm=p(pfx)+p(["a","o","ex","is","um","en","ia"])+" "+p(sfx)}while(u.has(nm));u.add(nm);var rnd=Math.random()*stot,cum=0,seg=skeys[0];for(var si=0;si<skeys.length;si++){cum+=SEG_W[skeys[si]];if(rnd<=cum){seg=skeys[si];break}}var revPLN=rf(500000000,82000000000);var profitPLN=revPLN*rf(0.05,0.7);var revBnEur=+(revPLN/4166000000).toFixed(2);var profitPct=+(profitPLN/revPLN*100).toFixed(1);var potSpend=+(revBnEur*rf(0.3,0.6)).toFixed(2);var isPrioritySeg=Math.random()<.79;var isMapped=Math.random()<.95;var isP1=isPrioritySeg&&isMapped?Math.random()<.52:false;var isP1Priv=isPrioritySeg&&isMapped&&isP1&&(Math.random()<.88);var stg=isP1Priv?"New suspects":"—";co.push({id:i+1,nip:r(1000000000,9999999999)+"",name:nm,segment:seg,subSegment:p(SUB_SEG[seg]),segPriority:isPrioritySeg?"Priority":"Non-priority",mapped:isPrioritySeg?isMapped:true,priority:isPrioritySeg&&isMapped?(isP1?"P1 - High priority":"P2 - Opportunistic"):"N/A",ownership:isPrioritySeg&&isMapped&&isP1?(isP1Priv?"Private":"Public"):"N/A",revenuePLN:Math.round(revPLN),profitPLN:Math.round(profitPLN),revenueBnEur:revBnEur,profitPct:profitPct,potentialSpendMEur:potSpend,cluster:Math.random()<.96?"New Prospect":"Current Client",score:rf(1.5,5),region:p(REGIONS),contactName:"",stage:stg,isNew:isP1Priv,addedAt:Date.now()-Math.random()*2592000000})}return co}

var PQ=[{cat:"STRATEGIC FIT",color:"#ef4444",items:[{id:"intent",name:"Intent to outsource FM",desc:"Is the client considering outsourcing?",q:["Considering outsourcing FM?","New need or reviewing?","What's driving this?"],w:3},{id:"scope",name:"Service scope",desc:"Which FM services are in scope?",q:["Which services?","One or multiple providers?","Could scope expand?"],w:2}]},{cat:"OPERATIONAL FIT",color:"#3b82f6",items:[{id:"ability",name:"AP ability to respond",desc:"Does opportunity fit AP capabilities?",q:["Key requirements?","Technical constraints?","Expected SLAs?"],w:3},{id:"geography",name:"Geography / sites",desc:"Where are services needed?",q:["Site locations?","How many sites?","Single or multi-site?"],w:2}]},{cat:"LEAD QUALITY",color:"#eab308",items:[{id:"competitor",name:"Competitor in place",desc:"Who's the current provider?",q:["Current provider?","Satisfaction?","Open to change?"],w:2},{id:"interest",name:"Interest level",desc:"How engaged is the client?",q:["Open to follow-up?","Priority level?"],w:2},{id:"need",name:"Pain points",desc:"Clear business need?",q:["FM challenges?","What to improve?","Ideal solution?"],w:1}]}];

/* ── Prospect File Fields (reorganized: Pre-meeting / Post-meeting) ── */
var PF_FIELDS=[
  {id:"contactName",l:"Contact Name",t:"text",s:"pre"},{id:"contactTitle",l:"Title / Role",t:"text",s:"pre"},{id:"contactEmail",l:"Email",t:"text",s:"pre"},{id:"contactPhone",l:"Phone",t:"text",s:"pre"},
  {id:"companyProfile",l:"Company Profile",t:"area",s:"pre"},{id:"currentProvider",l:"Current FM Provider",t:"text",s:"pre"},{id:"contractExpiry",l:"Contract Expiry",t:"text",s:"pre"},{id:"decisionMaker",l:"Decision Maker",t:"area",s:"pre"},{id:"keyPriorities",l:"Key Priorities / Sensitivities",t:"area",s:"pre"},
  {id:"meetingDate",l:"Meeting Date",t:"text",s:"post"},{id:"meetingType",l:"Meeting Type",t:"text",s:"post"},{id:"attendees",l:"Attendees",t:"text",s:"post"},{id:"expressedNeeds",l:"Needs Expressed",t:"area",s:"post"},{id:"painPoints",l:"Pain Points",t:"area",s:"post"},{id:"objections",l:"Objections",t:"area",s:"post"},{id:"nextStepsAgreed",l:"Next Steps Agreed",t:"area",s:"post"},
  {id:"debriefNotes",l:"Debrief Notes",t:"area",s:"post"},{id:"revisedProbability",l:"Win Probability",t:"text",s:"post"},{id:"nextActions",l:"AP Next Actions",t:"area",s:"post"},{id:"followUpDate",l:"Follow-up Date",t:"text",s:"post"},{id:"estimatedValue",l:"Est. Contract Value (PLN)",t:"text",s:"post"}
];
var PF_SECS=[{id:"pre",title:"Pre-meeting",icon:"◇"},{id:"post",title:"Post-meeting",icon:"●"}];

function useStore(){var[data,setData]=useState(function(){try{return JSON.parse(localStorage.getItem("at_v11")||"{}")}catch(e){return{}}});var save=function(id,key,val){setData(function(p){var next=Object.assign({},p);next[id]=Object.assign({},p[id]||{});next[id][key]=val;try{localStorage.setItem("at_v11",JSON.stringify(next))}catch(e){}return next})};var get=function(id){return data[id]||{}};var qual=function(id){var d=data[id];if(!d||!d.scores||!Object.keys(d.scores).length)return null;return getQ(calcWS(d.scores))};return{save:save,get:get,qual:qual,data:data}}

var cd={background:"#fff",borderRadius:10,border:"1px solid "+Bdr};
var inp={padding:"7px 10px",borderRadius:8,border:"1px solid "+Bdr,fontSize:13,fontFamily:F,outline:"none",color:Tx,boxSizing:"border-box",background:"#fff",width:"100%"};

/* ── Toast ── */
function useToast(){var[toasts,setT]=useState([]);var add=function(m,t){var id=Date.now();setT(function(p){return p.concat([{id:id,m:m,t:t||"info"}])});setTimeout(function(){setT(function(p){return p.filter(function(x){return x.id!==id})})},2200)};return{toasts:toasts,add:add}}
function Toasts(props){return<div style={{position:"fixed",bottom:20,right:20,zIndex:9999,display:"flex",flexDirection:"column",gap:6}}>{props.toasts.map(function(t){return<div key={t.id} style={{padding:"10px 16px",borderRadius:10,background:Dk,color:"#fff",fontSize:12,fontWeight:600,fontFamily:F,boxShadow:"0 8px 24px rgba(0,0,0,.25)",display:"flex",alignItems:"center",gap:8}}><span style={{width:6,height:6,borderRadius:20,background:t.t==="success"?"#22c55e":P}}/>{t.m}</div>})}</div>}

/* ── Onboarding ── */
function OnboardingTour(props){var[s,setS]=useState(0);var steps=[{t:"Welcome to Atalian Sales Excellence",d:"Your pipeline management tool for hunting new logos in Poland.",i:"A"},{t:"Home — Daily Cockpit",d:"Action items, hot leads, pipeline at a glance.",i:"→"},{t:"Hunt List — Target Companies",d:"4,300 companies. Filter, sort by CA/Priority, export.",i:"≡"},{t:"Pipeline — Kanban Board",d:"Drag prospects: New → To be contacted → Contacted → Pre-qualified → Handed-over. Sort by CA/Priority.",i:"◫"},{t:"Qualification — Score Leads",d:"7 criteria → Hot Lead, Cold Lead, or Not Relevant.",i:"◉"},{t:"Ready to hunt!",d:"Click any stage to start.",i:"✓"}];var st=steps[s];
  return<div style={{position:"fixed",inset:0,zIndex:10000,background:"rgba(0,0,0,.6)",display:"flex",alignItems:"center",justifyContent:"center",backdropFilter:"blur(8px)"}}><div style={{background:"#fff",borderRadius:16,padding:"32px",maxWidth:400,width:"90%",textAlign:"center"}}><div style={{width:48,height:48,borderRadius:12,background:Dk,color:P,display:"inline-flex",alignItems:"center",justifyContent:"center",fontSize:20,fontWeight:900,marginBottom:12}}>{st.i}</div><h2 style={{margin:"0 0 8px",fontSize:17,fontWeight:800,color:Tx}}>{st.t}</h2><p style={{margin:"0 0 20px",fontSize:13,color:Tx2,lineHeight:1.6}}>{st.d}</p><div style={{display:"flex",justifyContent:"center",gap:3,marginBottom:16}}>{steps.map(function(_,i){return<div key={i} style={{width:s===i?20:6,height:6,borderRadius:20,background:s===i?P:Bdr}}/>})}</div><div style={{display:"flex",gap:8,justifyContent:"center"}}>{s>0&&<button onClick={function(){setS(s-1)}} style={{padding:"8px 16px",borderRadius:8,border:"1px solid "+Bdr,background:"#fff",color:Tx2,fontWeight:600,fontSize:12,cursor:"pointer",fontFamily:F}}>Back</button>}{s<steps.length-1?<button onClick={function(){setS(s+1)}} style={{padding:"8px 20px",borderRadius:8,border:"none",background:Dk,color:"#fff",fontWeight:700,fontSize:12,cursor:"pointer",fontFamily:F}}>Next</button>:<button onClick={props.onDone} style={{padding:"8px 20px",borderRadius:8,border:"none",background:P,color:"#fff",fontWeight:700,fontSize:12,cursor:"pointer",fontFamily:F}}>Get Started</button>}<button onClick={props.onDone} style={{padding:"8px 12px",border:"none",background:"transparent",color:Tx3,fontSize:11,cursor:"pointer",fontFamily:F}}>Skip</button></div></div></div>}

/* ── Components ── */
function Sparkline(props){var c=props.color||P;var pts=useMemo(function(){var a=[];for(var i=0;i<12;i++)a.push(Math.random()*.5+.2+(i/12)*.4);return a},[]);var h=22,w=64;var mx=Math.max.apply(null,pts),mn=Math.min.apply(null,pts);var d="M"+pts.map(function(v,i){return(i/11*w).toFixed(1)+","+(h-(v-mn)/(mx-mn||1)*h).toFixed(1)}).join(" L");return<svg width={w} height={h} style={{display:"block"}}><path d={d+" L"+w+","+h+" L0,"+h+" Z"} fill={c} opacity=".08"/><path d={d} fill="none" stroke={c} strokeWidth="1.5" strokeLinecap="round"/></svg>}
function ScoreBtn(props){return<div style={{display:"flex",gap:3}}>{[1,2,3,4,5].map(function(n){return<button key={n} onClick={function(){props.onChange(n)}} style={{width:32,height:32,borderRadius:8,border:props.value===n?"2px solid "+props.color:"1.5px solid "+Bdr,background:props.value===n?props.color:"#fff",color:props.value===n?"#fff":Tx3,fontSize:12,fontWeight:700,cursor:"pointer",fontFamily:F,transition:"all .12s"}}>{n}</button>})}</div>}
function Gauge(props){var score=props.score;var q=getQ(score),pct=Math.min(score/5,1)*100;return<div style={{display:"flex",flexDirection:"column",alignItems:"center",gap:4}}><div style={{fontSize:24,fontWeight:800,color:Tx,lineHeight:1}}>{score>0?score.toFixed(1):"—"}<span style={{fontSize:11,fontWeight:500,color:Tx3}}> /5</span></div><div style={{width:"100%",position:"relative"}}><div style={{display:"flex",height:6,borderRadius:20,overflow:"hidden",background:Surf}}><div style={{flex:50,background:"#fca5a5"}}/><div style={{flex:26,background:"#93c5fd"}}/><div style={{flex:24,background:"#86efac"}}/></div>{score>0&&<div style={{position:"absolute",top:-1,left:pct+"%",transform:"translateX(-50%)",transition:"left .4s"}}><div style={{width:2,height:8,background:Tx,borderRadius:1}}/></div>}<div style={{display:"flex",justifyContent:"space-between",marginTop:2}}><span style={{fontSize:7,fontWeight:700,color:"#ef4444"}}>NR</span><span style={{fontSize:7,fontWeight:700,color:"#3b82f6"}}>Cold</span><span style={{fontSize:7,fontWeight:700,color:"#22c55e"}}>Hot</span></div></div>{q&&<span style={{padding:"2px 10px",borderRadius:6,fontSize:10,fontWeight:700,background:q.bg2,color:q.color}}>{q.label}</span>}</div>}
function StagePill(props){var s=props.stage,sm=props.small;return<span style={{display:"inline-flex",alignItems:"center",gap:3,padding:sm?"1px 6px":"2px 8px",borderRadius:6,fontSize:sm?9:10,fontWeight:600,color:STAGE_C[s]||Tx3,background:(STAGE_C[s]||"#6b7280")+"12"}}><span style={{fontSize:sm?8:9}}>{STAGE_IC[s]||"?"}</span>{s}</span>}

function Waterfall(props){var ref=useRef(),cRef=useRef();var[ww,setWW]=useState(500);useEffect(function(){var ro=new ResizeObserver(function(e){var w=e[0]&&e[0].contentRect.width;if(w>50)setWW(w)});if(cRef.current)ro.observe(cRef.current);return function(){ro.disconnect()}},[]);useEffect(function(){if(!ref.current||!props.total)return;var svg=d3.select(ref.current);svg.selectAll("*").remove();var steps=[{l:"Active",v:props.total,t:"total"},{l:"Non-prio",v:-props.nonPrio,t:"dec"},{l:"Priority",v:props.prio,t:"sub"},{l:"Unmapped",v:-props.notMapped,t:"dec"},{l:"P2",v:-props.p2,t:"dec"},{l:"P1",v:props.p1,t:"sub"},{l:"Public",v:-props.pub,t:"dec"},{l:"Private",v:props.priv,t:"fin"}];var h=180,m={top:16,right:8,bottom:36,left:36},iw=ww-m.left-m.right,ih=h-m.top-m.bottom;var g=svg.attr("viewBox","0 0 "+ww+" "+h).append("g").attr("transform","translate("+m.left+","+m.top+")");var x=d3.scaleBand().domain(steps.map(function(d){return d.l})).range([0,iw]).padding(.2);var y=d3.scaleLinear().domain([0,props.total*1.12]).range([ih,0]);var run=0;var bars=steps.map(function(s){var y0,y1;if(s.t==="total"||s.t==="sub"||s.t==="fin"){y0=0;y1=Math.abs(s.v);run=Math.abs(s.v)}else{y1=run;y0=run+s.v;run=y0}return{l:s.l,v:s.v,t:s.t,y0:y0,y1:y1}});for(var i=0;i<bars.length-1;i++){var c=bars[i],n=bars[i+1];var fy=c.t==="dec"?y(c.y0):y(c.y1);g.append("line").attr("x1",x(c.l)+x.bandwidth()).attr("x2",x(n.l)).attr("y1",fy).attr("y2",fy).attr("stroke",Bdr).attr("stroke-width",.5).attr("stroke-dasharray","3,2")}var bg=g.selectAll(".b").data(bars).join("g");bg.append("rect").attr("x",function(d){return x(d.l)}).attr("width",x.bandwidth()).attr("y",function(d){return y(Math.max(d.y0,d.y1))}).attr("height",0).attr("rx",3).attr("fill",function(d){return d.t==="total"?Dk:d.t==="sub"?Dk3:d.t==="fin"?P:"#e5e7eb"}).transition().duration(400).delay(function(_,i){return i*60}).attr("height",function(d){return Math.abs(y(d.y0)-y(d.y1))});bg.append("text").attr("x",function(d){return x(d.l)+x.bandwidth()/2}).attr("y",function(d){return y(Math.max(d.y0,d.y1))-4}).attr("text-anchor","middle").attr("font-size",9).attr("font-weight",700).attr("fill",Tx).attr("opacity",0).text(function(d){return Math.abs(d.v).toLocaleString()}).transition().duration(200).delay(function(_,i){return i*60+350}).attr("opacity",1);g.append("g").attr("transform","translate(0,"+ih+")").call(d3.axisBottom(x).tickSize(0)).selectAll("text").attr("font-size",8).attr("fill",Tx3);g.selectAll(".domain,.tick line").remove()},[props,ww]);return<div ref={cRef} style={{width:"100%"}}><svg ref={ref} style={{width:"100%",height:"auto"}}/></div>}

function exportCSV(data,cols,filename){var h=cols.map(function(c){return c.l}).join(",");var rows=data.map(function(co){return cols.map(function(c){var v=co[c.k];return typeof v==="string"&&v.includes(",")?'"'+v+'"':v}).join(",")});var blob=new Blob([h+"\n"+rows.join("\n")],{type:"text/csv"});var a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=filename||"export.csv";a.click()}

/* ── New Prospect Modal ── */
function NewProspectModal(props){var[name,setName]=useState("");var[seg,setSeg]=useState(SEGMENTS[0]);var[reg,setReg]=useState(REGIONS[0]);var[rev,setRev]=useState("");var ok=name.trim().length>0;
  return<div style={{position:"fixed",inset:0,zIndex:10000,background:"rgba(0,0,0,.5)",display:"flex",alignItems:"center",justifyContent:"center",backdropFilter:"blur(6px)"}} onClick={function(e){if(e.target===e.currentTarget)props.onClose()}}><div style={{background:"#fff",borderRadius:14,padding:"24px 28px",maxWidth:440,width:"92%",boxShadow:"0 24px 64px rgba(0,0,0,.2)"}}><h2 style={{margin:"0 0 16px",fontSize:16,fontWeight:800,color:Tx}}>New prospect</h2><div style={{display:"flex",flexDirection:"column",gap:10}}><div><label style={{fontSize:11,fontWeight:600,color:Tx2,display:"block",marginBottom:3}}>Company name</label><input value={name} onChange={function(e){setName(e.target.value)}} placeholder="e.g. Warszawa Logistics S.A." style={inp} autoFocus/></div><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:10}}><div><label style={{fontSize:11,fontWeight:600,color:Tx2,display:"block",marginBottom:3}}>Segment</label><select value={seg} onChange={function(e){setSeg(e.target.value)}} style={inp}>{SEGMENTS.map(function(s){return<option key={s}>{s}</option>})}</select></div><div><label style={{fontSize:11,fontWeight:600,color:Tx2,display:"block",marginBottom:3}}>Region</label><select value={reg} onChange={function(e){setReg(e.target.value)}} style={inp}>{REGIONS.map(function(r){return<option key={r}>{r}</option>})}</select></div></div><div><label style={{fontSize:11,fontWeight:600,color:Tx2,display:"block",marginBottom:3}}>Revenue (bn€)</label><input value={rev} onChange={function(e){setRev(e.target.value)}} type="number" placeholder="1.5" style={inp}/></div></div><div style={{display:"flex",gap:8,marginTop:16,justifyContent:"flex-end"}}><button onClick={props.onClose} style={{padding:"7px 16px",borderRadius:8,border:"1px solid "+Bdr,background:"#fff",color:Tx2,fontWeight:600,fontSize:12,cursor:"pointer",fontFamily:F}}>Cancel</button><button disabled={!ok} onClick={function(){var r2=parseFloat(rev)||1;props.onAdd({name:name.trim(),nip:Math.floor(Math.random()*9e9+1e9)+"",segment:seg,subSegment:SUB_SEG[seg][0],region:reg,ownership:"Private",cluster:"New Prospect",revenueBnEur:r2,profitPct:+(Math.random()*40+5).toFixed(1),potentialSpendMEur:+(r2*(.3+Math.random()*.3)).toFixed(2),score:3});props.onClose()}} style={{padding:"7px 20px",borderRadius:8,border:"none",background:ok?Dk:"#e5e7eb",color:ok?"#fff":"#9ca3af",fontWeight:700,fontSize:12,cursor:ok?"pointer":"default",fontFamily:F}}>Add</button></div></div></div>}

/* ── Company Panel (tabs: Overview / Pre-meeting / Post-meeting / Qualification) ── */
function CompanyPanel(props){var co=props.co,store=props.store,updateStage=props.updateStage,toast=props.toast;var s0=store.get(co.id);var[tab,setTab]=useState("overview");var[scores,setS]=useState(s0.scores||{});var[notes,setN]=useState(s0.notes||{});var[showQ,setSQ]=useState({});var[fields,setF]=useState(Object.assign({companyProfile:co.name+"\n"+co.segment+" · "+co.region+"\n"+co.revenueBnEur+"bn€"},s0.prospect||{}));
  useEffect(function(){store.save(co.id,"scores",scores);store.save(co.id,"notes",notes)},[scores,notes]);
  useEffect(function(){store.save(co.id,"prospect",fields)},[fields]);
  var ws=useMemo(function(){return calcWS(scores)},[scores]);var q=getQ(ws);
  var tot=PQ.reduce(function(s,c){return s+c.items.length},0);var done=Object.keys(scores).filter(function(k){return scores[k]}).length;var allDone=done>=tot;
  var finalize=function(){if(!q){toast("Score all 7 criteria first","warning");return}if(q.short==="Hot"){updateStage(co.id,"Pre-qualified");toast("→ Pre-qualified (Hot Lead)","success")}else if(q.short==="Cold"){updateStage(co.id,"Pre-qualified");toast("→ Pre-qualified (Cold Lead)","success")}else{toast("Marked as Not Relevant","info")}};
  // Notes summary for overview
  // Notes summary with section context (Pre-meeting → Field: value)
  var notesSummary=useMemo(function(){var parts=[];
    // Prospect fields (pre-meeting / post-meeting)
    PF_FIELDS.forEach(function(f){if(fields[f.id]&&typeof fields[f.id]==="string"&&fields[f.id].trim()&&f.id!=="companyProfile"){var secName=f.s==="pre"?"Pre-meeting":"Post-meeting";parts.push({section:secName,field:f.l,value:fields[f.id].trim().substring(0,100)})}});
    // Qualification notes
    PQ.forEach(function(c){c.items.forEach(function(it){if(notes[it.id]&&notes[it.id].trim()){parts.push({section:"Qualification",field:it.name,value:notes[it.id].trim().substring(0,100)})}})});
    return parts},[fields,notes]);
  var TABS=[{id:"overview",l:"Overview"},{id:"pre",l:"Pre-meeting"},{id:"post",l:"Post-meeting"},{id:"qualify",l:"Qualification"}];
  return<div style={{position:"fixed",inset:0,zIndex:1000,background:"rgba(0,0,0,.4)",backdropFilter:"blur(6px)"}} onClick={function(e){if(e.target===e.currentTarget)props.onClose()}}><div style={{position:"absolute",top:0,right:0,bottom:0,width:"min(680px,94vw)",background:Surf,overflowY:"auto",animation:"slideIn .2s ease-out"}}><style>{"@keyframes slideIn{from{transform:translateX(100%)}to{transform:translateX(0)}}"}</style>
    <div style={{background:Dk,padding:"16px 20px",position:"sticky",top:0,zIndex:10}}>
      <div style={{display:"flex",justifyContent:"space-between",alignItems:"flex-start"}}><div style={{flex:1,minWidth:0}}><h2 style={{margin:0,fontSize:15,fontWeight:700,color:"#fff",overflow:"hidden",textOverflow:"ellipsis",whiteSpace:"nowrap"}}>{co.name}</h2><div style={{display:"flex",gap:6,marginTop:6,alignItems:"center",flexWrap:"wrap"}}><span style={{fontSize:11,color:"rgba(255,255,255,.4)"}}>{co.segment} · {co.region} · {co.revenueBnEur}bn€</span><StagePill stage={co.stage}/>{q&&<span style={{padding:"1px 7px",borderRadius:5,fontSize:9,fontWeight:700,color:q.color,background:"rgba(255,255,255,.08)"}}>{q.label}</span>}</div></div><div style={{display:"flex",gap:4}}><button onClick={function(){toast("Saved","success")}} style={{padding:"5px 12px",borderRadius:7,border:"none",background:P,color:"#fff",fontWeight:700,fontSize:11,cursor:"pointer",fontFamily:F}}>Save</button><button onClick={props.onClose} style={{width:26,height:26,borderRadius:6,border:"none",background:"rgba(255,255,255,.08)",color:"rgba(255,255,255,.5)",fontSize:12,cursor:"pointer",display:"flex",alignItems:"center",justifyContent:"center"}}>✕</button></div></div>
      <div style={{display:"flex",gap:3,marginTop:8}}>{STAGES.map(function(st){return<button key={st} onClick={function(){updateStage(co.id,st);toast("→ "+st,"success")}} style={{padding:"2px 8px",borderRadius:5,border:"1px solid "+(co.stage===st?"transparent":(STAGE_C[st]||"#6b7280")+"30"),background:co.stage===st?(STAGE_C[st]||"#6b7280"):"transparent",color:co.stage===st?"#fff":(STAGE_C[st]||"#6b7280"),fontSize:9,fontWeight:600,cursor:"pointer",fontFamily:F}}>{STAGE_IC[st]} {st}</button>})}</div>
      <div style={{display:"flex",gap:2,marginTop:8}}>{TABS.map(function(t){return<button key={t.id} onClick={function(){setTab(t.id)}} style={{padding:"5px 12px",borderRadius:6,border:"none",cursor:"pointer",fontSize:11,fontWeight:600,fontFamily:F,background:tab===t.id?"rgba(255,255,255,.1)":"transparent",color:tab===t.id?"#fff":"rgba(255,255,255,.35)"}}>{t.l}</button>})}</div>
    </div>
    <div style={{padding:"14px 20px"}}>
      {/* OVERVIEW with notes summary */}
      {tab==="overview"&&<div>
        <div style={{display:"grid",gridTemplateColumns:"1fr 1fr 1fr",gap:8,marginBottom:12}}>{[["Revenue",co.revenueBnEur+"bn€",Tx],["Profit",co.profitPct+"%",Tx],["Pot. Spend",co.potentialSpendMEur+"m€",P]].map(function(r){return<div key={r[0]} style={Object.assign({},cd,{padding:"10px 12px"})}><div style={{fontSize:9,color:Tx3,fontWeight:600,textTransform:"uppercase"}}>{r[0]}</div><div style={{fontSize:18,fontWeight:800,color:r[2],marginTop:2}}>{r[1]}</div></div>})}</div>
        <div style={Object.assign({},cd,{padding:"12px 14px",marginBottom:10})}><Gauge score={ws}/></div>
        <div style={Object.assign({},cd,{padding:"12px 14px",marginBottom:10})}><div style={{fontSize:11,fontWeight:700,color:Tx,marginBottom:6}}>Company details</div><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:3,fontSize:11}}>{[["NIP",co.nip],["Cluster",co.cluster],["Priority",co.priority],["Ownership",co.ownership],["Segment",co.segment],["Region",co.region]].map(function(r){return<div key={r[0]}><span style={{color:Tx3}}>{r[0]}</span> <span style={{fontWeight:600}}>{r[1]}</span></div>})}</div></div>
        {/* Notes summary */}
        <div style={Object.assign({},cd,{padding:"12px 14px"})}><div style={{fontSize:11,fontWeight:700,color:Tx,marginBottom:6}}>Notes summary</div>{notesSummary.length>0?<div style={{display:"flex",flexDirection:"column",gap:2}}>{notesSummary.map(function(n,i){return<div key={i} style={{fontSize:11,padding:"4px 0",borderBottom:i<notesSummary.length-1?"1px solid "+Bdr:"none",display:"flex",gap:6,alignItems:"flex-start"}}><span style={{fontSize:9,fontWeight:700,color:P,background:P+"10",padding:"1px 6px",borderRadius:4,whiteSpace:"nowrap",flexShrink:0}}>{n.section}</span><span style={{color:Tx2}}><b style={{color:Tx}}>{n.field}:</b> {n.value}</span></div>})}</div>:<div style={{fontSize:12,color:Tx3,fontStyle:"italic"}}>No notes yet. Fill in Pre-meeting, Post-meeting or Qualification tabs.</div>}
        </div>
      </div>}
      {/* PRE-MEETING */}
      {tab==="pre"&&<div>{PF_SECS.filter(function(s){return s.id==="pre"}).map(function(sec){var sf=PF_FIELDS.filter(function(f){return f.s===sec.id});return<div key={sec.id}><div style={{fontSize:12,fontWeight:700,color:Tx,marginBottom:8}}>{sec.icon} {sec.title}</div><div style={Object.assign({},cd,{padding:"10px 12px",display:"flex",flexDirection:"column",gap:6})}>{sf.map(function(f){return<div key={f.id}><label style={{fontSize:10,fontWeight:600,color:Tx3,display:"block",marginBottom:2}}>{f.l}</label>{f.t==="area"?<textarea value={fields[f.id]||""} onChange={function(e){var id=f.id,v=e.target.value;setF(function(p){return Object.assign({},p,{[id]:v})})}} rows={3} style={inp}/>:<input value={fields[f.id]||""} onChange={function(e){var id=f.id,v=e.target.value;setF(function(p){return Object.assign({},p,{[id]:v})})}} style={inp}/>}</div>})}</div></div>})}</div>}
      {/* POST-MEETING */}
      {tab==="post"&&<div>{PF_SECS.filter(function(s){return s.id==="post"}).map(function(sec){var sf=PF_FIELDS.filter(function(f){return f.s===sec.id});return<div key={sec.id}><div style={{fontSize:12,fontWeight:700,color:Tx,marginBottom:8}}>{sec.icon} {sec.title}</div><div style={Object.assign({},cd,{padding:"10px 12px",display:"flex",flexDirection:"column",gap:6})}>{sf.map(function(f){return<div key={f.id}><label style={{fontSize:10,fontWeight:600,color:Tx3,display:"block",marginBottom:2}}>{f.l}</label>{f.t==="area"?<textarea value={fields[f.id]||""} onChange={function(e){var id=f.id,v=e.target.value;setF(function(p){return Object.assign({},p,{[id]:v})})}} rows={3} style={inp}/>:<input value={fields[f.id]||""} onChange={function(e){var id=f.id,v=e.target.value;setF(function(p){return Object.assign({},p,{[id]:v})})}} style={inp}/>}</div>})}</div></div>})}</div>}
      {/* QUALIFICATION */}
      {tab==="qualify"&&<div>
        <div style={Object.assign({},cd,{padding:"12px 16px",marginBottom:12,display:"flex",alignItems:"center",gap:16,flexWrap:"wrap",position:"sticky",top:58,zIndex:5,background:"#fff"})}>
          <div style={{flex:"0 0 auto"}}><Gauge score={ws}/></div>
          <div style={{flex:1,minWidth:120}}><div style={{fontSize:11,color:Tx2,marginBottom:4}}>{done}/{tot} criteria scored</div><div style={{height:5,background:Surf,borderRadius:20,overflow:"hidden"}}><div style={{height:"100%",width:(done/tot*100)+"%",background:allDone?(q?q.color:Tx3):P,borderRadius:20,transition:"width .3s"}}/></div>
            {PQ.map(function(cat){var cs=cat.items.filter(function(c){return scores[c.id]});var avg=cs.length?cs.reduce(function(s,c){return s+scores[c.id]},0)/cs.length:0;return<div key={cat.cat} style={{display:"flex",alignItems:"center",gap:6,marginTop:4}}><span style={{fontSize:8,fontWeight:700,color:cat.color,width:70,textTransform:"uppercase"}}>{cat.cat}</span><div style={{flex:1,height:3,background:Surf,borderRadius:20,overflow:"hidden"}}><div style={{height:"100%",width:(avg/5*100)+"%",background:cat.color,borderRadius:20}}/></div><span style={{fontSize:9,fontWeight:700,width:20,textAlign:"right"}}>{avg>0?avg.toFixed(1):"—"}</span></div>})}
          </div>
          <button onClick={finalize} style={{padding:"8px 18px",borderRadius:8,border:"none",background:allDone?(q?q.color:Tx3):Bdr,color:allDone?"#fff":Tx3,fontWeight:700,fontSize:12,cursor:allDone?"pointer":"default",fontFamily:F,opacity:allDone?1:.5}}>{allDone?(q?"Finalize: "+q.label:"Finalize"):"Score all criteria"}</button>
        </div>
        {PQ.map(function(cat){return<div key={cat.cat} style={{marginBottom:10}}><div style={{fontSize:10,fontWeight:700,textTransform:"uppercase",letterSpacing:".08em",color:cat.color,marginBottom:6}}>{cat.cat}</div>{cat.items.map(function(it){return<div key={it.id} style={Object.assign({},cd,{padding:"10px 12px",marginBottom:5,borderLeft:"2px solid "+(scores[it.id]?cat.color:Bdr)})}><div style={{fontSize:12,fontWeight:700,color:Tx,marginBottom:3}}>{it.name}</div><ScoreBtn value={scores[it.id]||0} onChange={function(v){var id=it.id;setS(function(p){var n=Object.assign({},p);n[id]=v;return n})}} color={cat.color}/><button onClick={function(){var id=it.id;setSQ(function(p){var n=Object.assign({},p);n[id]=!p[id];return n})}} style={{marginTop:3,background:"none",border:"none",cursor:"pointer",fontSize:10,color:P,fontFamily:F,padding:0,fontWeight:600}}>{showQ[it.id]?"▾":"▸"} Guide</button>{showQ[it.id]&&<div style={{marginTop:3,paddingLeft:8,borderLeft:"1.5px solid "+Bdr}}>{it.q.map(function(q2,i){return<p key={i} style={{margin:"1px 0",fontSize:10,color:Tx2}}>→ {q2}</p>})}</div>}<textarea placeholder="Notes…" value={notes[it.id]||""} onChange={function(e){var id=it.id,v=e.target.value;setN(function(p){var n=Object.assign({},p);n[id]=v;return n})}} rows={2} style={Object.assign({},inp,{marginTop:4,fontSize:12})}/></div>})}</div>})}
      </div>}
    </div>
  </div></div>}

/* ── Columns ── */
var COLS=[{k:"name",l:"Company",w:190},{k:"stage",l:"Stage",w:100},{k:"prequal",l:"Qual.",w:70},{k:"segment",l:"Segment",w:140},{k:"priority",l:"Priority",w:80},{k:"revenueBnEur",l:"Rev. (bn€)",w:80},{k:"potentialSpendMEur",l:"Spend (m€)",w:80},{k:"cluster",l:"Cluster",w:90},{k:"region",l:"Region",w:95},{k:"score",l:"Score",w:55}];

/* ══════════════ MAIN ══════════════ */
var PW_HASH="a]m#9Kx$Lp2!vQ"; // obfuscated check
function checkPw(v){return v==="SKAtalianPoland2026!"}

export default function App(){
  // Auth
  var[authed,setAuthed]=useState(function(){try{return sessionStorage.getItem("at_auth")==="1"}catch(e){return false}});
  var[pwInput,setPwInput]=useState("");var[pwErr,setPwErr]=useState(false);
  // App state — ALL hooks must be before any conditional return
  var[companies,setCo]=useState(function(){return genCo(4300)});
  var[view,setView]=useState("home");var[search,setSearch]=useState("");
  var[segF,setSegF]=useState("All");var[regF,setRegF]=useState("All");var[stageF,setStageF]=useState("All");
  var[sortK,setSortK]=useState("_caPrio");var[sortD,setSortD]=useState("desc");
  var[recency,setRecency]=useState("none");
  var[page,setPage]=useState(0);var[panel,setPanel]=useState(null);var[hovRow,setHovRow]=useState(null);
  var[visibleCols,setVisibleCols]=useState(function(){return["name","stage","prequal","segment","priority","revenueBnEur","potentialSpendMEur","cluster","region"]});
  var store=useStore();var PS=35;var toast=useToast();
  var[showTour,setShowTour]=useState(function(){try{return!localStorage.getItem("at_toured10")}catch(e){return true}});
  var[dragId,setDragId]=useState(null);var[showNew,setShowNew]=useState(false);
  var[kanbanSort,setKanbanSort]=useState("_caPrio");

  var updateStage=useCallback(function(id,stage){setCo(function(prev){return prev.map(function(c){return c.id===id?Object.assign({},c,{stage:stage}):c})})},[]);
  var addCo=useCallback(function(d){setCo(function(prev){var mx=prev.reduce(function(m,c){return Math.max(m,c.id)},0);return prev.concat([Object.assign({id:mx+1,segPriority:"Priority",mapped:true,priority:"P1 - High priority",ownership:d.ownership||"Private",revenuePLN:Math.round((d.revenueBnEur||1)*4166e6),profitPLN:0,stage:"New suspects",isNew:true,addedAt:Date.now()},d)])})},[]);
  var prioRank=function(c){return c.priority.includes("P1")?0:c.priority.includes("P2")?1:2};

  var qualMap=useMemo(function(){var m={};companies.forEach(function(c){m[c.id]=store.qual(c.id)});return m},[companies,store]);
  var filtered=useMemo(function(){var d=companies.slice();
    if(search){var q=search.toLowerCase();d=d.filter(function(c){return c.name.toLowerCase().includes(q)||c.nip.includes(q)})}
    if(segF!=="All")d=d.filter(function(c){return c.segment===segF});
    if(regF!=="All")d=d.filter(function(c){return c.region===regF});
    if(stageF!=="All")d=d.filter(function(c){return c.stage===stageF});
    d.sort(function(a,b){
      var primary;
      if(sortK==="_caPrio"){var pa=prioRank(a),pb=prioRank(b);primary=pa!==pb?pa-pb:b.revenueBnEur-a.revenueBnEur}
      else if(sortK==="priority"){var pa2=prioRank(a),pb2=prioRank(b);primary=sortD==="asc"?pa2-pb2:pb2-pa2}
      else{var av=a[sortK],bv=b[sortK];if(typeof av==="string"){av=av.toLowerCase();bv=bv.toLowerCase()}primary=sortD==="asc"?(av<bv?-1:av>bv?1:0):(av>bv?-1:av<bv?1:0)}
      if(primary!==0)return primary;
      if(recency==="newest")return(b.addedAt||0)-(a.addedAt||0);
      if(recency==="oldest")return(a.addedAt||0)-(b.addedAt||0);
      return 0});
    return d},[companies,search,segF,regF,stageF,sortK,sortD,recency]);
  var pg=filtered.slice(page*PS,(page+1)*PS),tp=Math.ceil(filtered.length/PS)||1;
  var hs=function(k){if(k==="priority"){setSortK("priority");setSortD(sortK==="priority"&&sortD==="asc"?"desc":"asc")}else if(sortK===k){setSortD(sortD==="asc"?"desc":"asc")}else{setSortK(k);setSortD("desc")}setPage(0)};

  var pipeHot=0,pipeCold=0,pipeNR=0;companies.forEach(function(c){var q=qualMap[c.id];if(q){if(q.short==="Hot")pipeHot++;else if(q.short==="Cold")pipeCold++;else pipeNR++}});
  var stageCounts={};var stageRev={};STAGES.forEach(function(s){var sc=companies.filter(function(c){return c.stage===s});stageCounts[s]=sc.length;stageRev[s]=Math.round(sc.reduce(function(a,c){return a+c.potentialSpendMEur},0))});
  var wfD=useMemo(function(){var t=companies.length;var np=companies.filter(function(c){return c.segPriority==="Non-priority"}).length;var pr=t-np;var nm=companies.filter(function(c){return c.segPriority==="Priority"&&!c.mapped}).length;var p2c=companies.filter(function(c){return c.segPriority==="Priority"&&c.mapped&&c.priority.includes("P2")}).length;var p1c=companies.filter(function(c){return c.segPriority==="Priority"&&c.mapped&&c.priority.includes("P1")}).length;var pubc=companies.filter(function(c){return c.segPriority==="Priority"&&c.mapped&&c.priority.includes("P1")&&c.ownership==="Public"}).length;return{t:t,np:np,pr:pr,nm:nm,p2c:p2c,p1c:p1c,pubc:pubc,privc:p1c-pubc}},[companies]);
  var hotLeads=useMemo(function(){return companies.filter(function(c){return qualMap[c.id]&&qualMap[c.id].short==="Hot"}).slice(0,8)},[companies,qualMap]);
  var contactedNoQual=useMemo(function(){return companies.filter(function(c){return c.stage==="Contacted"&&!qualMap[c.id]}).slice(0,5)},[companies,qualMap]);
  var top20=useMemo(function(){return companies.slice().sort(function(a,b){return b.potentialSpendMEur-a.potentialSpendMEur}).slice(0,20)},[companies]);
  var regionData=useMemo(function(){var m={};REGIONS.forEach(function(r){var rc=companies.filter(function(c){return c.region===r});m[r]={count:rc.length,spend:Math.round(rc.reduce(function(s,c){return s+c.potentialSpendMEur},0))}});return m},[companies]);
  var exportHotLeads=function(){var hots=companies.filter(function(c){return qualMap[c.id]&&qualMap[c.id].short==="Hot"});if(!hots.length){toast.add("No hot leads to export","warning");return}exportCSV(hots,COLS,"hot_leads_export.csv");toast.add("Exported "+hots.length+" hot leads","success")};

  var tryLogin=function(){if(checkPw(pwInput)){setAuthed(true);try{sessionStorage.setItem("at_auth","1")}catch(e){}}else{setPwErr(true);setTimeout(function(){setPwErr(false)},1500)}};

  // ── AUTH GATE ──
  if(!authed)return<div style={{fontFamily:F,minHeight:"100vh",background:Dk,display:"flex",alignItems:"center",justifyContent:"center"}}>
    <link href="https://fonts.googleapis.com/css2?family=DM+Sans:opsz,wght@9..40,100..1000&display=swap" rel="stylesheet"/>
    <div style={{background:"#fff",borderRadius:16,padding:"40px 36px",maxWidth:380,width:"90%",textAlign:"center"}}>
      <div style={{width:48,height:48,borderRadius:12,background:P,display:"inline-flex",alignItems:"center",justifyContent:"center",fontWeight:900,color:"#fff",fontSize:18,marginBottom:16}}>A</div>
      <h1 style={{margin:"0 0 4px",fontSize:20,fontWeight:800,color:Tx}}>Atalian Poland</h1>
      <p style={{margin:"0 0 24px",fontSize:13,color:Tx3}}>Sales Excellence Tool</p>
      <input type="password" value={pwInput} onChange={function(e){setPwInput(e.target.value);setPwErr(false)}} onKeyDown={function(e){if(e.key==="Enter")tryLogin()}} placeholder="Enter password" autoFocus style={{width:"100%",padding:"10px 14px",borderRadius:10,border:"1.5px solid "+(pwErr?"#ef4444":Bdr),fontSize:14,fontFamily:F,outline:"none",boxSizing:"border-box",textAlign:"center",color:Tx,background:pwErr?"#fee2e2":"#fff",transition:"all .2s"}}/>
      <button onClick={tryLogin} style={{width:"100%",marginTop:10,padding:"10px 0",borderRadius:10,border:"none",background:Dk,color:"#fff",fontSize:13,fontWeight:700,cursor:"pointer",fontFamily:F}}>Sign in</button>
      {pwErr&&<p style={{margin:"8px 0 0",fontSize:11,color:"#ef4444",fontWeight:600}}>Incorrect password</p>}
      <p style={{margin:"20px 0 0",fontSize:9,color:Tx3}}>Simon-Kucher × Atalian — Confidential</p>
    </div>
  </div>;

  return<div style={{fontFamily:F,background:Surf,minHeight:"100vh",color:Tx,display:"flex"}}>
    <link href="https://fonts.googleapis.com/css2?family=DM+Sans:opsz,wght@9..40,100..1000&display=swap" rel="stylesheet"/>
    <style>{`@keyframes fadeIn{from{opacity:0}to{opacity:1}}.v-fade{animation:fadeIn .2s ease-out both}.r-hover{transition:background .1s}.r-hover:hover{background:#f1f3f9 !important}`}</style>

    {showTour&&<OnboardingTour onDone={function(){setShowTour(false);try{localStorage.setItem("at_toured10","1")}catch(e){}}}/>}
    {showNew&&<NewProspectModal onClose={function(){setShowNew(false)}} onAdd={function(d){addCo(d);toast.add(d.name+" added","success")}}/>}
    <Toasts toasts={toast.toasts}/>
    {panel&&<CompanyPanel co={panel} store={store} updateStage={updateStage} toast={toast.add} onClose={function(){setPanel(null)}}/>}

    {/* ── SIDEBAR ── */}
    <nav style={{width:220,background:Dk,color:"#fff",padding:"16px 0",display:"flex",flexDirection:"column",position:"fixed",top:0,bottom:0,left:0,zIndex:100}}>
      <div style={{padding:"0 16px",marginBottom:20}}><div style={{display:"flex",alignItems:"center",gap:8}}><div style={{width:28,height:28,borderRadius:7,background:P,display:"flex",alignItems:"center",justifyContent:"center",fontWeight:900,color:"#fff",fontSize:12}}>A</div><div><div style={{fontSize:13,fontWeight:700}}>Atalian</div><div style={{fontSize:9,color:"rgba(255,255,255,.3)"}}>Sales Excellence</div></div></div></div>
      <div style={{display:"flex",flexDirection:"column",gap:1,padding:"0 8px"}}>{[{id:"home",l:"Home",ic:"⌂"},{id:"list",l:"Hunt List",ic:"≡"},{id:"kanban",l:"Pipeline",ic:"◫"},{id:"dashboard",l:"Analytics",ic:"◔"}].map(function(v){var active=view===v.id;return<button key={v.id} onClick={function(){setView(v.id);setPage(0)}} style={{display:"flex",alignItems:"center",gap:10,padding:"8px 12px",borderRadius:7,border:"none",cursor:"pointer",fontFamily:F,fontSize:12,fontWeight:active?600:400,background:active?"rgba(255,255,255,.08)":"transparent",color:active?"#fff":"rgba(255,255,255,.45)",textAlign:"left",width:"100%"}}><span style={{fontSize:14,width:18,textAlign:"center"}}>{v.ic}</span>{v.l}</button>})}</div>
      <div style={{margin:"auto 0 0",padding:"12px 16px",borderTop:"1px solid rgba(255,255,255,.06)"}}>
        <div style={{fontSize:9,color:"rgba(255,255,255,.3)",textTransform:"uppercase",letterSpacing:".1em",marginBottom:8}}>Qualification</div>
        {[{l:"Hot Lead",c:"#22c55e",n:pipeHot},{l:"Cold Lead",c:"#3b82f6",n:pipeCold},{l:"Not Relevant",c:"#ef4444",n:pipeNR}].map(function(p){return<div key={p.l} style={{display:"flex",alignItems:"center",gap:8,marginBottom:4}}><span style={{width:6,height:6,borderRadius:20,background:p.c}}/><span style={{fontSize:11,color:"rgba(255,255,255,.5)",flex:1}}>{p.l}</span><span style={{fontSize:12,fontWeight:700,color:p.c}}>{p.n}</span></div>})}
        <button onClick={function(){setShowNew(true)}} style={{width:"100%",marginTop:12,padding:"7px 0",borderRadius:7,border:"1px dashed rgba(255,255,255,.15)",background:"transparent",color:"rgba(255,255,255,.4)",fontSize:11,fontWeight:600,cursor:"pointer",fontFamily:F}} onMouseEnter={function(e){e.target.style.borderColor=P;e.target.style.color=P}} onMouseLeave={function(e){e.target.style.borderColor="rgba(255,255,255,.15)";e.target.style.color="rgba(255,255,255,.4)"}}>+ New prospect</button>
      </div>
    </nav>

    {/* ── MAIN ── */}
    <div style={{marginLeft:220,flex:1,minHeight:"100vh"}}><main style={{padding:"20px 28px 40px",maxWidth:1300,margin:"0 auto"}}>

      {/* HOME */}
      {view==="home"&&<div key="home" className="v-fade">
        <h1 style={{margin:"0 0 20px",fontSize:22,fontWeight:800,letterSpacing:"-0.02em"}}>Home</h1>
        <div style={{display:"grid",gridTemplateColumns:"repeat("+STAGES.length+",1fr)",gap:8,marginBottom:20}}>{STAGES.map(function(s){return<div key={s} onClick={function(){setView("list");setStageF(s)}} style={Object.assign({},cd,{padding:"12px 14px",cursor:"pointer",position:"relative",overflow:"hidden"})}><div style={{display:"flex",justifyContent:"space-between",alignItems:"flex-start"}}><div><div style={{fontSize:9,textTransform:"uppercase",letterSpacing:".1em",color:STAGE_C[s],fontWeight:700,marginBottom:2}}>{STAGE_IC[s]} {s}</div><div style={{fontSize:20,fontWeight:800,color:Tx}}>{stageCounts[s]}</div><div style={{fontSize:10,color:Tx3}}>{stageRev[s]}m€</div></div><Sparkline color={STAGE_C[s]}/></div><div style={{position:"absolute",bottom:0,left:0,right:0,height:2,background:STAGE_C[s],opacity:.5}}/></div>})}</div>
        <div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:12}}>
          <div style={Object.assign({},cd,{padding:"16px 18px"})}><div style={{fontSize:13,fontWeight:700,marginBottom:10}}>Action required</div>{contactedNoQual.length>0?contactedNoQual.map(function(c){return<div key={c.id} onClick={function(){setPanel(c)}} className="r-hover" style={{padding:"6px 8px",borderRadius:6,cursor:"pointer",fontSize:12,display:"flex",justifyContent:"space-between",marginBottom:2}}><span style={{fontWeight:600}}>{c.name}</span><span style={{color:Tx3,fontSize:11}}>{c.revenueBnEur}bn€</span></div>}):<div style={{padding:16,textAlign:"center",color:Tx3,fontSize:12}}>All caught up.</div>}</div>
          <div style={Object.assign({},cd,{padding:"16px 18px"})}><div style={{fontSize:13,fontWeight:700,marginBottom:10}}>Hot leads</div>{hotLeads.length>0?hotLeads.map(function(c){return<div key={c.id} onClick={function(){setPanel(c)}} className="r-hover" style={{padding:"6px 8px",borderRadius:6,cursor:"pointer",fontSize:12,display:"flex",gap:8,borderLeft:"2px solid #22c55e",marginBottom:2}}><span style={{fontWeight:600,flex:1}}>{c.name}</span><span style={{fontWeight:700,color:P}}>{c.potentialSpendMEur}m€</span></div>}):<div style={{padding:16,textAlign:"center",color:Tx3,fontSize:12}}>No hot leads yet.</div>}</div>
        </div>
        <div style={Object.assign({},cd,{padding:"16px 18px",marginTop:12})}><div style={{fontSize:13,fontWeight:700,marginBottom:8}}>Pipeline funnel</div><Waterfall total={wfD.t} nonPrio={wfD.np} prio={wfD.pr} notMapped={wfD.nm} p2={wfD.p2c} p1={wfD.p1c} pub={wfD.pubc} priv={wfD.privc}/></div>
      </div>}

      {/* HUNT LIST */}
      {view==="list"&&<div key="list" className="v-fade">
        <div style={{display:"flex",alignItems:"center",justifyContent:"space-between",marginBottom:14}}><h1 style={{margin:0,fontSize:22,fontWeight:800,letterSpacing:"-0.02em"}}>Hunt List</h1><div style={{display:"flex",gap:6}}><button onClick={function(){setShowNew(true)}} style={{padding:"6px 14px",borderRadius:7,border:"none",background:P,color:"#fff",fontSize:11,fontWeight:700,cursor:"pointer",fontFamily:F}}>+ New Prospect</button><button onClick={function(){exportCSV(filtered,COLS,"huntlist.csv");toast.add("Exported "+filtered.length+" rows","success")}} style={{padding:"6px 14px",borderRadius:7,border:"1px solid "+Bdr,background:"#fff",color:Tx2,fontSize:11,fontWeight:600,cursor:"pointer",fontFamily:F}}>Export CSV</button></div></div>
        <div style={{display:"flex",gap:4,marginBottom:10,flexWrap:"wrap",alignItems:"center"}}><button onClick={function(){setStageF("All");setPage(0)}} style={{padding:"5px 12px",borderRadius:6,border:"1px solid "+(stageF==="All"?Dk:Bdr),background:stageF==="All"?Dk:"#fff",color:stageF==="All"?"#fff":Tx2,fontSize:11,fontWeight:600,cursor:"pointer",fontFamily:F}}>All {companies.length}</button>{STAGES.map(function(s){return<button key={s} onClick={function(){setStageF(s);setPage(0)}} style={{padding:"5px 12px",borderRadius:6,border:"1px solid "+(stageF===s?STAGE_C[s]:Bdr),background:stageF===s?STAGE_C[s]+"10":"#fff",color:stageF===s?STAGE_C[s]:Tx2,fontSize:11,fontWeight:600,cursor:"pointer",fontFamily:F}}>{STAGE_IC[s]} {s} {stageCounts[s]}</button>})}</div>
        <div style={{display:"flex",gap:8,marginBottom:8,alignItems:"center",flexWrap:"wrap"}}>
          <input placeholder="Search…" value={search} onChange={function(e){setSearch(e.target.value);setPage(0)}} style={Object.assign({},inp,{width:200})}/>
          <select value={segF} onChange={function(e){setSegF(e.target.value);setPage(0)}} style={Object.assign({},inp,{width:"auto",cursor:"pointer"})}><option value="All">Segment</option>{SEGMENTS.map(function(o){return<option key={o}>{o}</option>})}</select>
          <select value={regF} onChange={function(e){setRegF(e.target.value);setPage(0)}} style={Object.assign({},inp,{width:"auto",cursor:"pointer"})}><option value="All">Region</option>{REGIONS.map(function(o){return<option key={o}>{o}</option>})}</select>
          {/* Sort: primary + sub-sort by recency */}
          <div style={{display:"flex",alignItems:"center",gap:3,padding:"3px 6px",background:"#f8f9fb",borderRadius:8,border:"1px solid "+Bdr}}>
            <span style={{fontSize:9,fontWeight:700,color:Tx2}}>Sort:</span>
            {[{k:"_caPrio",l:"CA/Prio"},{k:"revenueBnEur",l:"Revenue"},{k:"potentialSpendMEur",l:"Spend"},{k:"priority",l:"Priority",d:"asc"}].map(function(s){return<button key={s.k} onClick={function(){setSortK(s.k);setSortD(s.d||"desc");setPage(0)}} style={{padding:"2px 8px",borderRadius:5,border:"none",background:sortK===s.k?P:"transparent",color:sortK===s.k?"#fff":Tx3,fontSize:9,fontWeight:sortK===s.k?700:500,cursor:"pointer",fontFamily:F}}>{s.l}</button>})}
          </div>
          <div style={{display:"flex",alignItems:"center",gap:3,padding:"3px 6px",background:"#f8f9fb",borderRadius:8,border:"1px solid "+Bdr}}>
            <span style={{fontSize:9,fontWeight:700,color:Tx2}}>Then by:</span>
            {[{k:"none",l:"—"},{k:"newest",l:"Newest first"},{k:"oldest",l:"Oldest first"}].map(function(s){return<button key={s.k} onClick={function(){setRecency(s.k);setPage(0)}} style={{padding:"2px 8px",borderRadius:5,border:"none",background:recency===s.k?Dk:"transparent",color:recency===s.k?"#fff":Tx3,fontSize:9,fontWeight:recency===s.k?700:500,cursor:"pointer",fontFamily:F}}>{s.l}</button>})}
          </div>
          <span style={{fontSize:11,color:Tx3,marginLeft:"auto"}}>{filtered.length} results</span>
        </div>
        <div style={Object.assign({},cd,{padding:"6px 12px",marginBottom:8,display:"flex",alignItems:"center",gap:6,flexWrap:"wrap"})}><span style={{fontSize:10,fontWeight:700,color:Tx2}}>Columns</span>{COLS.map(function(col){var on=visibleCols.includes(col.k);return<button key={col.k} onClick={function(){setVisibleCols(function(p){return on?p.filter(function(k){return k!==col.k}):p.concat([col.k])})}} style={{padding:"2px 8px",borderRadius:5,border:"1px solid "+(on?P:Bdr),background:on?P+"10":"#fff",color:on?P:Tx3,fontSize:9,fontWeight:on?700:500,cursor:"pointer",fontFamily:F}}>{col.l}</button>})}<div style={{marginLeft:"auto",display:"flex",gap:3}}><button onClick={function(){setVisibleCols(COLS.map(function(c){return c.k}))}} style={{padding:"2px 8px",borderRadius:5,border:"1px solid "+Bdr,background:"#fff",color:Tx3,fontSize:9,cursor:"pointer",fontFamily:F}}>All</button><button onClick={function(){setVisibleCols(["name","stage","prequal","segment","potentialSpendMEur","region"])}} style={{padding:"2px 8px",borderRadius:5,border:"1px solid "+Bdr,background:"#fff",color:Tx3,fontSize:9,cursor:"pointer",fontFamily:F}}>Minimal</button></div></div>
        <div style={Object.assign({},cd,{overflow:"hidden"})}><div style={{overflowX:"auto"}}><table style={{width:"max-content",minWidth:"100%",borderCollapse:"collapse",fontSize:12}}><thead><tr>{COLS.filter(function(c){return visibleCols.includes(c.k)}).map(function(c){return<th key={c.k} onClick={function(){hs(c.k)}} style={{padding:"7px 10px",textAlign:"left",fontSize:10,fontWeight:600,color:sortK===c.k?Tx:Tx3,borderBottom:"1px solid "+Bdr,cursor:"pointer",whiteSpace:"nowrap",minWidth:c.w,background:"#fff"}}>{c.l}{sortK===c.k?(sortD==="asc"?" ↑":" ↓"):""}</th>})}<th style={{background:"#fff",borderBottom:"1px solid "+Bdr,width:50}}></th></tr></thead>
          <tbody>{pg.map(function(c,i){var q=qualMap[c.id];var isH=hovRow===c.id;var bg=isH?"#f1f3f9":i%2===0?"#fff":"#fafbfd";
            function rc(col){var v=c[col.k];if(col.k==="name")return<span style={{display:"inline-flex",alignItems:"center",gap:4}}><span style={{fontWeight:600,color:Tx,cursor:"pointer"}} onClick={function(){setPanel(c)}}>{v}</span>{c.isNew&&<span style={{padding:"1px 5px",borderRadius:4,fontSize:8,fontWeight:800,background:"#22c55e",color:"#fff",letterSpacing:".05em"}}>NEW</span>}</span>;if(col.k==="stage")return<StagePill stage={v} small/>;if(col.k==="prequal")return q?<span style={{padding:"1px 6px",borderRadius:4,fontSize:10,fontWeight:700,color:q.color,background:q.bg2}}>{q.short}</span>:<span style={{color:Bdr2}}>—</span>;if(col.k==="segment")return<span style={{display:"inline-flex",alignItems:"center",gap:4}}><span style={{width:7,height:7,borderRadius:2,background:SEGC[v]||"#ccc"}}/><span style={{fontSize:11}}>{v}</span></span>;if(col.k==="priority")return<span style={{fontSize:11,fontWeight:600,color:v.includes("P1")?P:Tx3}}>{v.includes("P1")?"P1":"P2"}</span>;if(col.k==="cluster")return<span style={{padding:"2px 8px",borderRadius:5,fontSize:10,fontWeight:600,background:v==="New Prospect"?"#fef3c7":"#dcfce7",color:v==="New Prospect"?"#a16207":"#166534"}}>{v==="New Prospect"?"Prospect":"Client"}</span>;if(col.k==="score")return<span style={{fontWeight:700}}>{Number(v).toFixed(1)}</span>;if(col.k==="potentialSpendMEur")return<span style={{fontWeight:600,color:P}}>{Number(v).toFixed(1)}</span>;if(typeof v==="number")return<span>{v>1e6?(v/1e9).toFixed(2):v.toFixed?v.toFixed(2):v}</span>;return<span>{v||"—"}</span>}
            return<tr key={c.id} className="r-hover" style={{background:bg,borderLeft:q?"2px solid "+q.color:"2px solid transparent"}} onMouseEnter={function(){setHovRow(c.id)}} onMouseLeave={function(){setHovRow(null)}}>{COLS.filter(function(col){return visibleCols.includes(col.k)}).map(function(col){return<td key={col.k} style={{padding:"6px 10px",borderBottom:"1px solid "+Bdr,whiteSpace:"nowrap"}}>{rc(col)}</td>})}<td style={{borderBottom:"1px solid "+Bdr,padding:"6px 8px"}}><button onClick={function(){setPanel(c)}} style={{padding:"3px 10px",borderRadius:6,border:"none",background:P,color:"#fff",fontSize:10,fontWeight:700,cursor:"pointer",fontFamily:F,opacity:isH?1:.15}}>Open</button></td></tr>})}</tbody></table></div></div>
        <div style={{display:"flex",justifyContent:"center",gap:6,marginTop:10}}><button disabled={page===0} onClick={function(){setPage(page-1)}} style={{padding:"4px 12px",borderRadius:6,border:"1px solid "+Bdr,background:"#fff",fontSize:11,fontFamily:F,color:Tx,fontWeight:600}}>←</button><span style={{fontSize:11,color:Tx3,padding:"4px 0"}}>{page+1} / {tp}</span><button disabled={page>=tp-1} onClick={function(){setPage(page+1)}} style={{padding:"4px 12px",borderRadius:6,border:"1px solid "+Bdr,background:"#fff",fontSize:11,fontFamily:F,color:Tx,fontWeight:600}}>→</button></div>
      </div>}

      {/* KANBAN */}
      {view==="kanban"&&<div key="kanban" className="v-fade">
        <div style={{display:"flex",alignItems:"center",justifyContent:"space-between",marginBottom:8,flexWrap:"wrap",gap:8}}>
          <h1 style={{margin:0,fontSize:22,fontWeight:800,letterSpacing:"-0.02em"}}>Pipeline</h1>
          <div style={{display:"flex",gap:6,alignItems:"center",flexWrap:"wrap"}}>
            <div style={{display:"flex",alignItems:"center",gap:3,padding:"3px 6px",background:"#f8f9fb",borderRadius:8,border:"1px solid "+Bdr}}>
              <span style={{fontSize:9,fontWeight:700,color:Tx2}}>Sort:</span>
              {[{k:"_caPrio",l:"CA/Prio"},{k:"revenueBnEur",l:"Revenue"},{k:"potentialSpendMEur",l:"Spend"}].map(function(s){return<button key={s.k} onClick={function(){setKanbanSort(s.k)}} style={{padding:"2px 8px",borderRadius:5,border:"none",background:kanbanSort===s.k?P:"transparent",color:kanbanSort===s.k?"#fff":Tx3,fontSize:9,fontWeight:kanbanSort===s.k?700:500,cursor:"pointer",fontFamily:F}}>{s.l}</button>})}
            </div>
            <div style={{display:"flex",alignItems:"center",gap:3,padding:"3px 6px",background:"#f8f9fb",borderRadius:8,border:"1px solid "+Bdr}}>
              <span style={{fontSize:9,fontWeight:700,color:Tx2}}>Then by:</span>
              {[{k:"none",l:"—"},{k:"newest",l:"Newest first"},{k:"oldest",l:"Oldest first"}].map(function(s){return<button key={s.k} onClick={function(){setRecency(s.k)}} style={{padding:"2px 8px",borderRadius:5,border:"none",background:recency===s.k?Dk:"transparent",color:recency===s.k?"#fff":Tx3,fontSize:9,fontWeight:recency===s.k?700:500,cursor:"pointer",fontFamily:F}}>{s.l}</button>})}
            </div>
            <button onClick={exportHotLeads} style={{padding:"6px 14px",borderRadius:8,border:"none",background:"#22c55e",color:"#fff",fontSize:11,fontWeight:700,cursor:"pointer",fontFamily:F,display:"flex",alignItems:"center",gap:4}}>⬇ Export {pipeHot} Hot Leads</button>
          </div>
        </div>
        <div style={{display:"grid",gridTemplateColumns:"repeat("+STAGES.length+",1fr)",gap:8,overflowX:"auto"}}>{STAGES.map(function(stage){
          var sc=companies.filter(function(c){return c.stage===stage}).sort(function(a,b){
            var primary;
            if(kanbanSort==="_caPrio"){var pa=a.priority.includes("P1")?0:a.priority.includes("P2")?1:2;var pb=b.priority.includes("P1")?0:b.priority.includes("P2")?1:2;primary=pa!==pb?pa-pb:b.revenueBnEur-a.revenueBnEur}
            else{primary=b[kanbanSort]-a[kanbanSort]}
            if(primary!==0)return primary;
            if(recency==="newest")return(b.addedAt||0)-(a.addedAt||0);
            if(recency==="oldest")return(a.addedAt||0)-(b.addedAt||0);
            return 0
          }).slice(0,25);
          return<div key={stage} onDragOver={function(e){e.preventDefault();e.currentTarget.style.background=STAGE_C[stage]+"08"}} onDragLeave={function(e){e.currentTarget.style.background=Surf}} onDrop={function(e){e.currentTarget.style.background=Surf;if(dragId){updateStage(dragId,stage);toast.add("→ "+stage,"success");setDragId(null)}}} style={{background:Surf,borderRadius:10,padding:8,minWidth:180,minHeight:200,border:"1px solid "+Bdr}}>
            <div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:4,padding:"2px 4px"}}><span style={{fontSize:11,fontWeight:700,color:STAGE_C[stage]}}>{STAGE_IC[stage]} {stage}</span><span style={{fontSize:10,fontWeight:600,color:Tx3}}>{stageCounts[stage]}</span></div>
            <div style={{fontSize:9,color:Tx3,marginBottom:6,padding:"0 4px"}}>{stageRev[stage]}m€</div>
            {sc.map(function(c){var q=qualMap[c.id];return<div key={c.id} draggable="true" onDragStart={function(){setDragId(c.id)}} onClick={function(){setPanel(c)}} style={{background:"#fff",borderRadius:8,padding:"7px 9px",marginBottom:4,cursor:"grab",border:"1px solid "+Bdr,borderLeft:"2px solid "+(q?q.color:STAGE_C[stage])}}><div style={{display:"inline-flex",alignItems:"center",gap:4,width:"100%"}}><span style={{fontSize:11,fontWeight:600,color:Tx,overflow:"hidden",textOverflow:"ellipsis",whiteSpace:"nowrap",flex:1}}>{c.name}</span>{c.isNew&&<span style={{padding:"0px 4px",borderRadius:3,fontSize:7,fontWeight:800,background:"#22c55e",color:"#fff"}}>NEW</span>}</div><div style={{display:"flex",justifyContent:"space-between",marginTop:2}}><span style={{fontSize:9,color:Tx3}}>{c.priority.includes("P1")?"P1":"P2"} · {c.revenueBnEur}bn€</span><span style={{fontSize:9,fontWeight:700,color:P}}>{c.potentialSpendMEur}m€</span></div>{q&&<span style={{padding:"1px 5px",borderRadius:4,fontSize:8,fontWeight:700,color:q.color,background:q.bg2}}>{q.short}</span>}</div>})}
            {stageCounts[stage]>25&&<div style={{textAlign:"center",fontSize:9,color:Tx3,padding:4}}>+{stageCounts[stage]-25} more</div>}
          </div>})}</div>
      </div>}

      {/* ANALYTICS */}
      {view==="dashboard"&&<div key="dash" className="v-fade">
        <h1 style={{margin:"0 0 16px",fontSize:22,fontWeight:800,letterSpacing:"-0.02em"}}>Analytics</h1>
        <div style={{display:"grid",gridTemplateColumns:"repeat(4,1fr)",gap:8,marginBottom:16}}>{[{l:"Qual. Rate",v:(companies.length?Math.round((pipeHot+pipeCold+pipeNR)/companies.length*100):0)+"%",s:(pipeHot+pipeCold+pipeNR)+"/"+companies.length,c:Tx},{l:"Hot Lead Rate",v:(pipeHot+pipeCold+pipeNR?Math.round(pipeHot/(pipeHot+pipeCold+pipeNR)*100):0)+"%",s:pipeHot+" hot",c:"#22c55e"},{l:"Active Pipeline",v:(stageRev["Contacted"]||0)+(stageRev["Pre-qualified"]||0)+"m€",s:"in progress",c:P},{l:"Handed-over",v:(stageRev["Handed-over"]||0)+"m€",s:(stageCounts["Handed-over"]||0)+" deals",c:"#22c55e"}].map(function(k){return<div key={k.l} style={Object.assign({},cd,{padding:"12px 14px"})}><div style={{fontSize:9,color:Tx3,fontWeight:600,textTransform:"uppercase"}}>{k.l}</div><div style={{display:"flex",alignItems:"flex-end",justifyContent:"space-between",marginTop:2}}><span style={{fontSize:22,fontWeight:800,color:k.c}}>{k.v}</span><Sparkline color={k.c}/></div><div style={{fontSize:10,color:Tx3,marginTop:2}}>{k.s}</div></div>})}</div>
        <div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:12,marginBottom:12}}>
          <div style={Object.assign({},cd,{padding:"16px 18px"})}><div style={{fontSize:13,fontWeight:700,marginBottom:10}}>Conversion funnel</div>{STAGES.map(function(s,i,arr){var cnt=stageCounts[s];var prev=i>0?stageCounts[arr[i-1]]:0;var rate=prev>0?Math.round(cnt/prev*100):-1;var mx=stageCounts[STAGES[0]]||1;return<div key={s} style={{display:"flex",alignItems:"center",gap:6,marginBottom:4}}><span style={{width:90,fontSize:10,fontWeight:600,color:STAGE_C[s],textAlign:"right"}}>{STAGE_IC[s]} {s}</span><div style={{flex:1,height:18,background:Surf,borderRadius:3,overflow:"hidden",position:"relative"}}><div style={{height:"100%",width:(cnt>0?Math.max(cnt/mx*100,2):0)+"%",background:STAGE_C[s],borderRadius:3}}/><span style={{position:"absolute",left:6,top:"50%",transform:"translateY(-50%)",fontSize:9,fontWeight:700,color:cnt/mx>.15?"#fff":Tx}}>{cnt}</span></div>{i>0&&<span style={{fontSize:10,fontWeight:600,color:rate<0?Bdr2:rate>=50?"#22c55e":rate>=20?P:"#ef4444",minWidth:30,textAlign:"right"}}>{rate<0?"—":rate+"%"}</span>}</div>})}</div>
          <div style={Object.assign({},cd,{padding:"16px 18px"})}><div style={{fontSize:13,fontWeight:700,marginBottom:10}}>Revenue by stage</div>{STAGES.map(function(s){var v=stageRev[s];var mx=Math.max.apply(null,STAGES.map(function(x){return stageRev[x]}))||1;return<div key={s} style={{display:"flex",alignItems:"center",gap:6,marginBottom:4}}><span style={{width:90,fontSize:10,fontWeight:600,color:STAGE_C[s],textAlign:"right"}}>{STAGE_IC[s]} {s}</span><div style={{flex:1,height:16,background:Surf,borderRadius:3,overflow:"hidden",position:"relative"}}><div style={{height:"100%",width:Math.max(v/mx*100,1)+"%",background:STAGE_C[s],borderRadius:3,opacity:.7}}/><span style={{position:"absolute",left:6,top:"50%",transform:"translateY(-50%)",fontSize:9,fontWeight:700,color:Tx}}>{v}m€</span></div></div>})}</div>
        </div>
        <div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:12}}>
          <div style={Object.assign({},cd,{padding:"16px 18px"})}><div style={{fontSize:13,fontWeight:700,marginBottom:10}}>Regional spend</div>{REGIONS.slice().sort(function(a,b){return regionData[b].spend-regionData[a].spend}).map(function(r){var d=regionData[r];var mx=Math.max.apply(null,REGIONS.map(function(x){return regionData[x].spend}))||1;var mn=Math.min.apply(null,REGIONS.map(function(x){return regionData[x].spend}));var t=(d.spend-mn)/(mx-mn||1);var hc=t>.66?"#ef4444":t>.33?P:"#3b82f6";return<div key={r} style={{display:"flex",alignItems:"center",gap:6,marginBottom:3}}><span style={{width:100,fontSize:10,fontWeight:500,color:Tx2,textAlign:"right",overflow:"hidden",textOverflow:"ellipsis",whiteSpace:"nowrap"}}>{r}</span><div style={{flex:1,height:14,background:Surf,borderRadius:3,overflow:"hidden"}}><div style={{height:"100%",width:Math.max(t*100,4)+"%",background:hc,borderRadius:3,opacity:.6}}/></div><span style={{fontSize:9,fontWeight:700,minWidth:40,textAlign:"right"}}>{d.spend}m€</span></div>})}</div>
          <div style={Object.assign({},cd,{padding:"16px 18px"})}><div style={{fontSize:13,fontWeight:700,marginBottom:10}}>Top 20 prospects</div><div style={{maxHeight:280,overflowY:"auto"}}>{top20.map(function(c,i){var q=qualMap[c.id];return<div key={c.id} onClick={function(){setPanel(c)}} className="r-hover" style={{display:"flex",alignItems:"center",gap:6,padding:"4px 6px",borderRadius:5,cursor:"pointer",marginBottom:1}}><span style={{width:16,fontSize:10,fontWeight:700,color:i<3?P:Tx3,textAlign:"center"}}>{i+1}</span><span style={{flex:1,fontSize:11,fontWeight:600,overflow:"hidden",textOverflow:"ellipsis",whiteSpace:"nowrap"}}>{c.name}</span>{q&&<span style={{fontSize:8,fontWeight:700,color:q.color}}>{q.short}</span>}<span style={{fontSize:10,fontWeight:700,color:P}}>{c.potentialSpendMEur}m€</span></div>})}</div></div>
        </div>
        <div style={Object.assign({},cd,{padding:"16px 18px",marginTop:12})}><div style={{fontSize:13,fontWeight:700,marginBottom:8}}>Pipeline funnel</div><Waterfall total={wfD.t} nonPrio={wfD.np} prio={wfD.pr} notMapped={wfD.nm} p2={wfD.p2c} p1={wfD.p1c} pub={wfD.pubc} priv={wfD.privc}/></div>
      </div>}

    </main></div>
  </div>}
